// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvmenyuothubdjupvdyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2bWVueXVvdGh1YmRqdXB2ZHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTEyMzYsImV4cCI6MjA2NTgyNzIzNn0.bviQosRY8QUu1rSsSeRURQQzEPDzxFpL-lu3hCcWPXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);